### ISSUE TITLE
Toggle buttons visibility inside  "View Settings" view

### ISSUE THREAD

**Issue by soymanuvalle** [PDFTron/pdftron-react-native#242]
Hello, for the app I'm developing we need hide/show the buttons located inside this view dynamically.

![image](https://user-images.githubusercontent.com/9582420/113069543-f49d3f00-9196-11eb-8af1-0253c6a76efb.png)

How could we do this? If it isn't supported yet, could you give me an orientation of how could I do this with native iOS code please?

Thanks

**Comment by JamesTron** [comment]
Hi,

We don't have a great way to customize this view at the moment. It is _possible_ to customize it because it is a `UITableViewController`, so you could subclass it (in native) and override the standard methods to remove rows, and also intercept row selections and change the `indexPath` that you send to the superclass to make sure the correct behaviour is realized. Hacky, but it would work.

You could also consider creating the view from scratch, with the code to customize to your apps specific needs right there.

Either way, the source code for the view is included in the .dmg download of our SDK, and I've also [included it here](https://github.com/PDFTron/pdftron-react-native/files/6288918/PTDocumentViewSettingsController.m.zip) for your convenience/reference. 

If you choose to go the subclass route, we have a guide on how to do so here:

https://www.pdftron.com/documentation/ios/guides/tools/customization/#override-classes

The subclass would be entirely implemented in the ReactNative wrapper, and using the above override system described in the guide, it would use your class instead of the standard one. Note that the call to `overrideClass:` must be done _before_ the viewer is instantiated.

Please let us know if you have any questions.

**Comment by soymanuvalle** [comment]
> Hi,
> 
> We don't have a great way to customize this view at the moment. It is _possible_ to customize it because it is a `UITableViewController`, so you could subclass it (in native) and override the standard methods to remove rows, and also intercept row selections and change the `indexPath` that you send to the superclass to make sure the correct behaviour is realized. Hacky, but it would work.
> 
> You could also consider creating the view from scratch, with the code to customize to your apps specific needs right there.
> 
> Either way, the source code for the view is included in the .dmg download of our SDK, and I've also [included it here](https://github.com/PDFTron/pdftron-react-native/files/6288918/PTDocumentViewSettingsController.m.zip) for your convenience/reference.
> 
> If you choose to go the subclass route, we have a guide on how to do so here:
> 
> https://www.pdftron.com/documentation/ios/guides/tools/customization/#override-classes
> 
> The subclass would be entirely implemented in the ReactNative wrapper, and using the above override system described in the guide, it would use your class instead of the standard one. Note that the call to `overrideClass:` must be done _before_ the viewer is instantiated.
> 
> Please let us know if you have any questions.

Thank you very much, I started working on it with subclasses a couple days ago but I was having trouble trying to keep the same design. With what you sent I'm sure it's gonna be much easier!

Regarding the override I wasn't aware of that feature, thanks

I'll re-open if something goes wrong
