### ISSUE TITLE
Crash app when open the document after iOS pdftron version updated

### ISSUE THREAD

**Issue by hatn98** [PDFTron/pdftron-react-native#267]
**Describe the bug**
When I open the document (I build with `react-native-pdftron` latest master version and `PDFNet (9.0.0.77669) Pod`) - crash app with error:  `RNTPTDocumentView.m:1616:28: 'controlsHidden' - Thread 1: EXC_BAD_ACCESS (code=1, address=0x20)`

**Steps to Reproduce the Problem**
1. Create new react app or replace "react-native-pdftron": "file:../" in example app for "react-native-pdftron": github:PDFTron/pdftron-react-native
2. Install all dependencies
3. Open a file pdf by "react-native-pdftron"

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: `iOS`

**Comment by exotexot** [comment]
Same

**Comment by JamieDass** [comment]
Hi,

Thanks for bringing this to our attention, we are investigating.

**Comment by JamieDass** [comment]
Hi @hatn98 and @exotexot,

We have implemented a fix for this crash and it's available in our stable nightly iOS build.

Are you able to try it by modifying the linked podspec in the Podfile as described here:
https://github.com/PDFTron/pdftron-react-native#ios

so that it reads:
`pod 'PDFNet', podspec: 'https://nightly-pdftron.s3-us-west-2.amazonaws.com/stable/2021-04-28/9.0/cocoapods/pdfnet/2021-04-28_stable_rev77684.podspec'`

and then re-running `pod install`.

Please let us know if that works for you.

**Comment by hatn98** [comment]
Hi @JamieDass,

I tried PDFNet version nightly and it worked.

**Comment by exotexot** [comment]
I can confirm, using @JamieDass's .podspec does solve the issue! Thanks. :)

**Comment by JamieDass** [comment]
Great thank you for checking! I'll close the issue now.

**Comment by exotexot** [comment]
Will you merge these changes to latest.podspec? 
Here, it still references 
.version  = '9.0.0.77669'

**Comment by exotexot** [comment]
Please merge these changes to latest.podspec though.

**Comment by JamieDass** [comment]
@exotexot These changes will be available in `latest.podspec` with the next release of the native iOS SDK, scheduled for the end of this month or early June.

In the meantime the stable nightly build is suitable production and is supported in the same way as an official release.
