### ISSUE TITLE
Cannot edit/delete reply added on web by the same user

### ISSUE THREAD

**Issue by damianimashaun** [PDFTron/pdftron-react-native#536]
**Describe the bug**
On Android, the context menu icon (three dots) is not displayed beside the reply, so there's no way to edit/delete the reply.

On iOS, you can long press and see the menu but after editing comment, callback `onExportAnnotationCommand` is not called so the change is not saved

![Screenshot_20220328-171956_Hive](https://user-images.githubusercontent.com/49630919/160442967-c893aaa8-9eab-459b-9929-6b2141e1372c.jpg)
_second reply is added on android_

**Steps to Reproduce the Problem**
On web, Add annotation with comment, Add reply
Open on mobile
Try to edit reply

**Expected behavior**
any reply can be edited on iOS/android

**Platform/Device Information (please complete the following information if applicable):**
 - Platform: iOS and Android
 - Device: [e.g. iPhone6, Google Pixel 4]
 - OS: [e.g. iOS8.1, Android Nougat]

**Additional context**
[xfdf_array.txt](https://github.com/PDFTron/pdftron-react-native/files/8364630/xfdf_array.txt)

**Comment by sgong-pdftron** [comment]
@damianimashaun we'll take a look and get back to you as soon as we can, in the future, please contact support directly (https://www.pdftron.com/support/) to avoid delays.

**Comment by ama-pdftron** [comment]
@damianimashaun 

The native PDFTron iOS SDK has been updated with a fix for the issue of the `onExportAnnotationCommand` not being called upon editing comments. If you are using the https://pdftron.com/downloads/ios/react-native/latest.podspec CocoaPod podspec then you can run the `pod update PDFNet` command from your project's ios/ directory to get the new version.

For Android, the fix for not being able to edit/delete reply is available if you update to the latest version of react native.
