### ISSUE TITLE
How do I enable tools (e.g. signature and drawing)

### ISSUE THREAD

**Issue by timkomip** [PDFTron/pdftron-react-native#9]
When using `DocumentVIew`, there is a `disabledTools` prop but no prop for enabling tools. Passing `disabledTools` an empty array or removing it does not seem to do anything.

What I have:
![image](https://user-images.githubusercontent.com/3844352/60917437-f7d3f700-a25e-11e9-84d8-40ed16bcfa8d.png)

What I want (sort of. just want signature tool):
![image](https://user-images.githubusercontent.com/3844352/60917473-07534000-a25f-11e9-8129-f25c23684d45.png)

**Comment by dluco-pdftron** [comment]
Hi @timkomip,
You can "enable" tools (eg. signature and freehand drawing) by disabling all the other tool types. The full list of tool type constants you'll want is here:
https://github.com/PDFTron/pdftron-react-native/blob/083c929c2ec4daecc3fe4c0b947ec185df1dee4f/src/Config/Config.js#L31-L50
The `annotationCreateFreeHand` and `annotationCreateSignature` values should be left out so that those aren't disabled.

**Comment by timkomip** [comment]
@dluco-pdftron  That does not seem to be working. I always end up with just the grab tool button. I set both `disabledElements` and `disabledTools` props with many different sets of values and I can't get it to show. 

Plus, an empty array should show all tools (?) but it does not.

**Comment by timkomip** [comment]
I also ran the example (which I had issues running. Had to update to RN 58.6 and reference pdftron-react-native from git instead of '..') and it also doesn't show any tool buttons besides grab tool.

**Comment by dluco-pdftron** [comment]
Hi @timkomip,
Commit e9412cd0c1d163c01544039c16252012b6ebcfe4 addresses the problem where the hand is the only thing in the toolbar. You should be able to use the `disabledTools` prop now.
Please let us know how this works for you!

**Comment by dluco-pdftron** [comment]
Closing this issue - please re-open if you have any problems. Thanks!
